# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8

# Fabric loader version. It's independent against MC versions
fabricLoomVersion=1.16-SNAPSHOT
fabricLoaderVersion=0.19.2
mod_version=1.5.0
mod_group=com.mndk
mod_id=bteterrarenderer
mod_authors=m4ndeokyi, Amrsatrio, Zoriot
mod_displayName=BTETerraRenderer
mod_description=Renders various external maps as a hologram for BuildTheEarth project.
mod_url=https://modrinth.com/mod/bteterrarenderer
mod_sourceUrl=https://github.com/BuildTheEarth/BTETerraRenderer
mod_discordUrl=https://discord.gg/gmPNqtWXmC
mod_credits=Authored by m4ndeokyi, updated by Amrsatrio, logo by d1m4 (vicrobex)
mod_license=Apache-2.0