["fabric26.1"]
minecraftVersion = "~26.1"
modLoaderName = "fabric"
fabricVersion = "0.145.1+26.1"
aw = "26.1.accesswidener"

["fabric1.21.11"]
minecraftVersion = "~1.21.11"
modLoaderName = "fabric"
fabricVersion = "0.141.3+1.21.11"
aw = "1.21.6.accesswidener"

["fabric1.21.10"]
minecraftVersion = "1.21.10"
modLoaderName = "fabric"
fabricVersion = "0.138.4+1.21.10"
aw = "1.21.6.accesswidener"

["fabric1.21.9"]
minecraftVersion = "1.21.9"
modLoaderName = "fabric"
fabricVersion = "0.134.1+1.21.9"
aw = "1.21.6.accesswidener"

["fabric1.21.6"]
minecraftVersion = ">=1.21.6 <=1.21.8"
modLoaderName = "fabric"
fabricVersion = "0.128.2+1.21.6"
aw = "1.21.6.accesswidener"

["fabric1.21.5"]
minecraftVersion = "1.21.5"
modLoaderName = "fabric"
fabricVersion = "0.128.2+1.21.5"
aw = "1.21.2.accesswidener"

["fabric1.21.4"]
minecraftVersion = "1.21.4"
modLoaderName = "fabric"
fabricVersion = "0.119.4+1.21.4"
aw = "1.21.2.accesswidener"

["fabric1.21.2"]
minecraftVersion = ">=1.21.2 <=1.21.3"
modLoaderName = "fabric"
fabricVersion = "0.106.1+1.21.2"
aw = "1.21.2.accesswidener"

["fabric1.21"]
minecraftVersion = ">=1.21 <=1.21.1"
modLoaderName = "fabric"
fabricVersion = "0.102.0+1.21"
aw = "1.21.accesswidener"

["fabric1.20.5"]
minecraftVersion = "~1.20.5"
modLoaderName = "fabric"
fabricVersion = "0.97.8+1.20.5"
aw = "1.20.accesswidener"

["fabric1.20.3"]
minecraftVersion = ">=1.20.3 <=1.20.4"
modLoaderName = "fabric"
fabricVersion = "0.91.1+1.20.3"
aw = "1.20.accesswidener"

["fabric1.20.2"]
minecraftVersion = "1.20.2"
modLoaderName = "fabric"
fabricVersion = "0.91.6+1.20.2"
aw = "1.20.accesswidener"

["fabric1.20"]
minecraftVersion = ">=1.20 <=1.20.1"
modLoaderName = "fabric"
fabricVersion = "0.83.0+1.20"
aw = "1.20.accesswidener"

["fabric1.19.4"]
minecraftVersion = "~1.19.4"
modLoaderName = "fabric"
fabricVersion = "0.87.2+1.19.4"
aw = "1.19.4.accesswidener"

["fabric1.19.3"]
minecraftVersion = "1.19.3"
modLoaderName = "fabric"
fabricVersion = "0.76.1+1.19.3"
aw = "1.19.4.accesswidener"

["fabric1.19"]
minecraftVersion = ">=1.19 <=1.19.2"
modLoaderName = "fabric"
fabricVersion = "0.58.0+1.19"
aw = "1.18.accesswidener"

["fabric1.18.1"]
minecraftVersion = "~1.18.1"
modLoaderName = "fabric"
fabricVersion = "0.46.6+1.18"
aw = "1.18.accesswidener"

["fabric1.18"]
minecraftVersion = "1.18"
modLoaderName = "fabric"
fabricVersion = "0.44.0+1.18"
aw = "1.18.accesswidener"
